<?php

// Traduzido por Marcelo Leães
// marcelo@eth1.com.br - Eth1 Consultoria

$labels = array();
$labels['autoreply'] = 'Auto-resposta';
$labels['changeautoreply'] = 'Adicionar uma auto-resposta';
$labels['enabled'] = 'Habilitado';
$labels['subject'] = 'Assunto';
$labels['message'] = 'Mensagem';
$labels['expires'] = 'Expira em';
$messages = array();
$messages['successfullyupdated'] = 'Auto-resposta foi atualizada com sucesso.';
$messages['internalerror'] = 'Ocorreu um erro com a ação selecionada.';
//$messages['connecterror'] = $messages['internalerror'] . ' Erro de conexão.';
$messages['loaderror'] = 'Não foi possivel carregar auto-resposta.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Erro de conexão.';
$messages['updateerror'] = 'Não foi possivel atualizar auto-resposta.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Erro de conexão.';
